// ON PAGE RELOAD
export const PAGE_REALOAD_GET_LOCAL_STORAGE_SAGA = 'PAGE_REALOAD_GET_LOCAL_STORAGE_SAGA';
export const PAGE_REALOAD_GET_LOCAL_STORAGE_OK = 'PAGE_REALOAD_GET_LOCAL_STORAGE_OK';
export const PAGE_REALOAD_GET_LOCAL_STORAGE_FAIL = 'PAGE_REALOAD_GET_LOCAL_STORAGE_FAIL';
// GET DATA
export const GET_DATA_SAGA = 'GET_DATA_SAGA';
export const GET_DATA_OK = 'GET_DATA_OK';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
// ON VIDEO CARD CLICKED from ("/search")
export const ON_VIDEO_CARD_CLICKED = 'ON_VIDEO_CARD_CLICKED';
// ON VIDEO CARD CLICKED FROM ("/videoPlay")
export const ON_VIDEO_CARD_CLICKED_VIDEO_PLAY = 'ON_VIDEO_CARD_CLICKED_VIDEO_PLAY';
// CREATE NEW PLAYLIST && REMOVE PLAYLIST
export const CREATE_NEW_PLAYLIST = 'CREATE_NEW_PLAYLIST';
export const REMOVE_PLAYLIST = 'REMOVE_PLAYLIST';
// ON SEARCH FROM HISTORY
export const ON_SEARCH_FROM_HISTORY_SAGA = 'ON_SEARCH_FROM_HISTORY_SAGA';
export const ON_SEARCH_FROM_HISTORY_OK = 'ON_SEARCH_FROM_HISTORY_OK';
export const ON_SEARCH_FROM_HISTORY_FAIL = 'ON_SEARCH_FROM_HISTORY_FAIL';
// PLAY VIDEO FROM HISTORY
export const PLAY_VIDEO_FROM_HISTORY = 'PLAY_VIDEO_FROM_HISTORY';
// ITEM MOVE TO PLAYLIST && REMOVE ITEM FROM PLAYLIST && DELETE ALL FROM PLAYLIST
export const ITEM_MOVE_TO_PLAYLIST = 'ITEM_MOVE_TO_PLAYLIST';
export const REMOVE_ITEM_FROM_PLAYLIST = 'REMOVE_ITEM_FROM_PLAYLIST';
export const DELETE_ALL_FROM_PLAYLIST = 'DELETE_ALL_FROM_PLAYLIST';
///// AUTH /////
// ON TRY AUTO SIGNUP
export const ON_TRY_AUTO_SIGNUP_SAGA = 'ON_TRY_AUTO_SIGNUP_SAGA';
// ANONYMOUS LOGIN
export const ANONYMOUS_LOGIN = 'ANONYMOUS_LOGIN';
// GOOGLE LOGIN
export const GOOGLE_LOGIN_SAGA = 'GOOGLE_LOGIN_SAGA';
export const GOOGLE_LOGIN_OK = 'GOOGLE_LOGIN_OK';
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL';
// LOGOUT
export const AUTH_LOGOUT_SAGA = 'AUTH_LOGOUT_SAGA';
export const AUTH_LOGOUT_OK = 'AUTH_LOGOUT_OK';
export const AUTH_LOGOUT_CLEAR = 'AUTH_LOGOUT_CLEAR';
export const LOGOUT_CLEAR_VIDEOS = 'LOGOUT_CLEAR_VIDEOS';
